import {images} from "../../../configs";
const aboutGlobalInputConfig={
  title:"About Global Input App",
  content:[
    "Global Input App provides a single app solution for encrypted data storage (including a password manager), encrypted data transfer between devices, encrypted QR Code creator & scanner, mobile input & control for smart TV, media device, IoT and web applications.",
    "In the Global Input App, everything is stored encrypted in your device's storage, and nothing stored outside your device. Your data stays encrypted even in memory, and decrypted only when needed.  There is no subscription, nor database on the server to store your data or your details. Your login password is not stored anywhere. It is used only as an encryption key to encrypt an encryption key, which is, in turn, used for encrypting the rest of the data in the app. Hence there is no way to recover your password if your forgot it.  Global Input App allows you to create and manage encryption keys, and select any of them to encrypt the rest of the data in the app. You can share encryption key via password protected QR codes. You can use encrypted QR codes to backup or share confidential contents.",
    "Global Input App provides a single mobile app solution in implementing mobile input and mobile control in the Smart TV, set-top box, IoT and web applications. The communication between the app and the applications uses the end-to-end encryption. The app scans the QR code, which is displayed by the application, to obtain the encryption key for the end-to-end encryption and the other communication parameters. The applications can declaratively specifies the UI (User Interface) elements for the callback functions for receiving events when the user interacts with the UI elements. This provides a unique solution in implementing a mobile input and control without doing mobile application development. The application can also take advantage of the encrypted data storage to allow user to store the data in app's storage to automate some operation, such as sign in, subscription, filling application forms and much more.",
    {type:"line", content:["Global Input App is a free app, created by Dr. Dilshat Hewzulla (", {type:"a", content:"dilshat@iterativesolution.co.uk", href:"dilshat@iterativesolution.co.uk"},") to resolve some common security issues faced daily in the business environments."]}
]

};
export default aboutGlobalInputConfig;
