const images={
  downward:require('../images/downward-link.png'),
  companyLogo:require('../images/company-logo.png'),
  globalInput:require('../images/global-input.png'),
  globalInputBackground: require("../images/glbal-input-header.png"),
  playstore:require("../images/play-store.png"),
  appstore:require("../images/app-store.png"),
  storeBackground:require("../images/store-background.png"),
  arrowDownToApply:require("../images/arrow-down-to-apply.png"),
  enableGlobalInput:require("../images/global-apply.png"),
  globalInputBanner:require("../images/global-input-banner.png"),
  endToEnd:require("../images/end-to-end.png"),
  passwordPrinting:require("../images/password-printing.png"),
  identification:require("../images/identification.png"),
  automateProcess:require("../images/automate-process.png"),
  documentBackground:require("../images/document-background.png"),
  appIcon:require("../images/globalInput-100.png"),
  globalInputApp:require("../images/global-input-app.png"),
  contentTransfer:require("../images/content-transfer.png"),
  encryptedQRCode:require("../images/encrypted-qr-code.png"),
  showSecret:require("../images/show-icon.png"),
  hideSecret:require("../images/hide-icon.png"),
  showSecretOver:require("../images/show-icon-over.png"),
  hideSecretOver:require("../images/hide-icon-over.png"),
  transferForm:require("../images/transfer-form.png"),
  chromeExtension:require("../images/chrome-extension.png"),
}
export default images;
