export const styles={
  row:{
    display:"flex",
    flexDirection:"row",
    justifyContent:"flex-start",

    marginBottom:"20",
    marginLeft:"4vw"
  },
  label:{
    fontSize:"1vw",
    color:"#5291CD",
    minWidth:200
  },
  fieldValue:{
    fontSize:"1vw",
    color:"#5291CD",
  },
  fieldContainer:{

  },
  form:{
    minWidth:"90%",
    borderRadius:25
  },
  buttons:{
    marginTop:10,
    display:"flex",
    flexDirection:"row",
    justifyContent:"space-around"
  },
  title:{
    display:"flex",
    flexDirection:"row",
    width:"100%",
    justifyContent:"flex-start",
    fontSize:"2vw",
    color:"#5291CD",
    marginBottom:"20",
    marginLeft:"4vw"
  },
  connectionMessage:{
    fontSize:"1vw",
    color:"#5291CD",
  },
  note:{
    fontSize:10,
    color:"#5291CD",
  },
  help:{
    fontSize:"2vw",
    color:"#5291CD",
    display:"flex",
    flexDirection:"row",
    width:"100%",
    height:"100%",
    justifyContent:"center",
    alignItems:"center",

  }

}
