import React from 'react';
import {Link} from 'react-router-dom';
import {styles,images} from './styles';

import BorderedWhite from '../../page-components/themes/bordered-white';

import {examplesLinks,externalsLinks} from '../../links-components';



const {ListAllExamples}=examplesLinks;

const {WebSocketServer,WatchIntroduction}=externalsLinks;

export default class MobileIntegration extends React.Component{

  static menu={
        id:"clientdevice",
        label:"Mobile Integration"
  }
  render(){
    const {P, Title, Code,Concept, FirstSection,NextSection}=this.props.theme;
    return(
      <React.Fragment>

            <FirstSection>
              <WatchIntroduction>Watch Intro</WatchIntroduction>

                  <Title>Mobile Integration</Title>
                    <P>
  Global Input App (GIA) provides applications with end-to-end encrypted communication across devices,
  using the <Concept>Encrypted QR Code technology</Concept>.

  This secure device-to-device communication allows applications to implement mobile integration
  that does not require any extra server-side implementations.
</P>
<P>
  It allows applications to specify mobile user interfaces and receive mobile events, thus being able to implement
  cross-devices business logic within the single application context.
   </P>
   <P>
  For example, if an application running on a device needs to display a button on the connected mobile device,
  the application can simply pass the following to the <Concept>GIA extension</Concept>:

                    <Code>
                      {`
        type:  "button",
        label: "Play",
        onInput:() => playMovie()
                      `}
                    </Code>
As the result of the above configuration data, the button that is displayed on the user's mobile will have the label of <Concept>Play</Concept>,
and
the <Concept>playMovie()</Concept> function will be invoked when user presses the button.


  </P>

                    <P>
  If a Smart TV application needs to receive user inputs via mobile to search media programmes,
  it may pass the following to the extension to achieve this:
                    </P>
                    <Code>
                      {`
       type:  "text",
       label: "Search",
       onInput:value => searchContent(value)
                      `}
                    </Code>
                    <P>
The above configuration will display a text field on the user's mobile with the label <Concept>Search</Concept>, and the <Concept>searchContent()</Concept> function
will be invoked with the value in the search field when the user types on the field.
</P>
<P>
Please try out the following example applications, and exmaine their sources codes on the Github to find out how the applications implements the mobile integration logics:
                    </P>
                    <ListAllExamples {...this.props}/>


                    <P>

The mobile operations are always started with scanning of an <Concept>Encrypted QR Code</Concept>,
which contains a <Concept>one-time-use encryption key</Concept> for the end-to-end encryption.
The encryption key is generated by the application on-the-fly and displayed as part of the QR Code, so it can
only be obtained via camera instead of via network.

This means that even if the HTTPS communication is compromised due to a compromised
                      CA (Certificate Authority) and an active MitM (man-in-the-middle) attack, the communication between devices will still be safe.
                    </P>
                    <P>
                        The QR code also contains other communication parameters for successfully establishing communication with the device application:
                        the URL to a <WebSocketServer {...this.props}>WebSocket proxy server </WebSocketServer>;
                        the API Key required by the <WebSocketServer {...this.props}>WebSocket server</WebSocketServer>, the Security Group ID required by the device application itself, and the connection session id.

 The WebSocket server is responsible for routing the encrypted messages between devices.

                    </P>

            </FirstSection>

    </React.Fragment>
    );
  }


}
